COORDINATES_MUST_NON_EMPTY = 'The coordinates must be non-empty'
COORDINATES_MUST_ITERABLE = 'The coordinates must be an iterable'
VECTORS_NOT_OF_SAME_DIMENSIONS = 'Vectors must have same dimensions'
ZERO_VECTOR_CAN_NOT_BE_NORMALIZED = 'Zero vector can not be normalized'
NO_UNIQUE_PARALLEL_COMPONENT_OF_PROJECTION = 'No unique parallel component of projection'
NO_UNIQUE_ORTHOGONAL_COMPONENT_OF_PROJECTION = 'No unique orthogonal component of projection'
ONLY_ALLOWED_FOR_TWO_THREE_DIM_VECTOR = 'Only allowed for two/three dimension vectors'
NO_NONZERO_ELEMENTS_FOUND = 'No non-zero elements found'
